version: '2'
services:
    www1:
        image: nginx
        container_name: www1
        ports:
            - 80
        volumes:
            - ./www1:/usr/share/nginx/html:ro
    
    www2:
        image: nginx
        container_name: www2
        ports:
            - 80
        volumes:
            - ./www2:/usr/share/nginx/html:ro

    haproxy:
        image: haproxy
        container_name: haproxy
        ports:
            - 80:80
        volumes:
            - ./haproxy:/usr/local/etc/haproxy:ro
        links:
            - www1:server1
            - www2:server2
        depends_on:
            - www1
            - www2
